### ISSUE TITLE
Elder/Shaped item background missing

### ISSUE THREAD

**Issue by eps1lon** [PoE-Profile/poe-profile#13]
First off: I've been using your website for close to a year now and I'm really happy you went open source!

Actual issue:
Example profile: http://poe-profile.info/profile/raizqt/RaizWhatEvenHabbenQT
Amulet, Ring and Gloves are missing the elder/shaper background. 

The poe [get-items](https://www.pathofexile.com/character-window/get-items?accountName=raizqt&character=RaizWhatEvenHabbenQT) api sets properties for `elder`/`shaper` to true if the background should be displayed.

**Comment by IvanD87** [comment]
Thanks for the reports, should be fixed now.

**Comment by eps1lon** [comment]
Seems like you forgot to give `.Amulet .icon` width and height. Currently not showing elder background for the amulet in the mentioned profile because the icon has no width.

Other issues seem to be resolved. 

Do you have any plans to invalidate the cache? This currently prevents a fast deploy of asset related bug fixes. Not sure how your build pipeline is set up so I can't offer any solution. Got way to comfortable with webpack and its automatic filename hashing.

**Comment by IvanD87** [comment]
Amulet css is fixed.
We recently added cache busting for our js, have yet to do this for css we don't have much experience with webpack .
